name: Build

on:
  push:
    branches:
      - main  #

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: NPM Install
        run: npm install
        
      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build -t swiggy-clone .
          docker tag swiggy-clone gyenoch/swiggy-clone:latest # Change gyenoch to your username
          docker login -u ${{ secrets.Dockerhub_username }} -p ${{ secrets.Dockerhub_token }}
          docker push gyenoch/swiggy-clone:latest
        env:
          DOCKER_CLI_ACI: 1
  deploy:
   needs: build
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull gyenoch/swiggy-clone:latest
      - name: Image scan
        run: trivy image gyenoch/swiggy-clone:latest > trivyimagedeploy.txt
      - name: Deploy to container
        run: docker run -d --name swiggy-clone1 -p 3000:3000 gyenoch/swiggy-clone:latest
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml
